heat_template_version: 2013-05-23

description: Heat Exercise 1

parameters:
  key_name:
    type: string
    label: key name
    default: badi-india-key
  image_id:
    type: string
    label: Image name
    default: futuresystems/ubuntu-14.04
  instance_type:
    type: string
    label: Instance flavor
    default: m1.small

resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: int-net
      security_groups:
        - default
        - { get_resource: secgroup }

  instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - port: { get_resource: instance_port }
